#! /bin/sh

sxhkd &
${HOME}/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap  10
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus true

# some extra top space for bar
bspc config top_padding    0
bspc config right_padding  8
bspc config left_padding   8
bspc config bottom_padding 0

bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitor true
bspc config merge_overlapping_monitors true

# Visual options
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config paddingless_monocle   false
bspc config single_monocle       true
bspc config focus_follows_pointer false
bspc config click_to_focus        true
bspc config split_ratio           0.50
bspc config focused_border_color  "#5e81ac"


bspc rule -a 'Zathura'       state=tiled
bspc rule -a sxiv                state=floating center=true
bspc rule -a Lxappearance        state=floating center=true focus=on
bspc rule -a gimp                state=floating
